name: MLOps Lambda Container Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Zip lambda layer content
        run: |
          mkdir python
          pip install -r requirements.txt -t python             
          zip --quiet -r packages.zip python
          ls -la

      - name: Zip Source Code Directory
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r src.zip src
        
     
      - name: Send Lambda Code to S3 and Layer Content         
        run: |
          aws s3api put-object --bucket twitter-context-analyser --key lambda-code/src.zip --region us-west-2 --body ./src.zip
          aws s3api put-object --bucket twitter-context-analyser --key lambda-layer/packages.zip --region us-west-2 --body ./packages.zip
      
      - name: Create Lambda Function
        run: | 
          aws cloudformation deploy \
            --stack-name tweet-context-analyser \
            --no-fail-on-empty-changeset \
            --template-file ./IaC/infra.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code --function-name tweet-context-analyser-Function-fNouBu0iur8e --s3-bucket twitter-context-analyser --s3-key lambda-code/src.zip



      