name: MLOps Lambda Container Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Zip Source Code Directory
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r src.zip src
        
      - name: verify files on directory
        run: |
          ls -la
      
      - name: Send Lambda Code to S3
        run: |
          aws s3api put-object --bucket twitter-context-analyser --key lambda-code/src.zip --region us-west-2 --body ./src.zip
      
      - name: Create Lambda Function
        run: | 
          aws cloudformation deploy \
            --stack-name tweet-context-analyser \
            --no-fail-on-empty-changeset \
            --template-file ./IaC/infra.yml \
            --capabilities CAPABILITY_NAMED_IAM


      